# Generated by Django 4.0.3 on 2022-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_remove_demandabsence_student_delete_absence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='annee',
            field=models.CharField(choices=[('2020-2021', '2021'), ('2021-2022', '2022'), ('2022-2023', '2023'), ('2023-2024', '2024'), ('2024-2025', '2025')], max_length=9),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fonction',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Professeur', 'Professeur'), ('Surveillant général', 'Surveillant général'), ('Surveillant', 'Surveillant'), ('Eleve', 'Eleve')], max_length=30, null=True),
        ),
    ]
