# Generated by Django 4.0.3 on 2022-03-20 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0004_remove_demandabsence_student_delete_absence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDeb', models.DateField(default=datetime.datetime.today, verbose_name='Début')),
                ('dateFin', models.DateField(default=datetime.datetime.today, verbose_name='Fin')),
                ('heureDeb1', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='De')),
                ('heureDeb2', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='De')),
                ('heureFin1', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='A')),
                ('heureFin2', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='A')),
                ('type', models.CharField(blank=True, choices=[('Cérémonie', 'Cérémonie'), ('Séminaire', 'Séminaire'), ('Salaire', 'Salaire'), ('Convenance personnelle', 'Convenance personnelle'), ('Santé', 'Santé')], max_length=25, verbose_name='Type Absence')),
                ('status', models.BooleanField(default=False, verbose_name='Justifiée')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAbs', models.DateField(default=datetime.datetime.today, verbose_name='Début')),
                ('heureDeb', models.TimeField(default=datetime.datetime.now, verbose_name='De')),
                ('heureFin', models.TimeField(default=datetime.datetime.now, verbose_name='A')),
                ('type', models.CharField(blank=True, choices=[('Absence', 'ABSENCE'), ('Retard', 'RETARD'), ('Sortie', 'SORTIE')], max_length=25, verbose_name='Type Absence')),
                ('justified', models.BooleanField(default=False, verbose_name='Justifiée')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
    ]
