# Generated by Django 4.0.3 on 2022-03-23 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='dateAbs',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.CharField(choices=[('Absence', 'ABSENCE'), ('Retard', 'RETARD'), ('Sortie', 'SORTIE')], max_length=25, verbose_name='Type Absence'),
        ),
    ]
